#!/bin/sh
#
# defaults:
#

mbt="$VG $mbt_bin/mbt"
mbtg="$VG $mbt_bin/mbtg"
mbts="$VG $mbt_bin/mbtserver"

\rm ./tests/*.out
\rm ./tests/*.%
\rm ./tests/*.tree

if test -d ./temp
then
    \rm ./temp/*
else
    \mkdir ./temp
fi

$mbtg -T tests/eindh.data -s ./temp/mbt.settings

$mbts -s ./temp/mbt.settings --logfile=/tmp/mbtjsonserver.log --pidfile=/tmp/mbtpid -S 2345 --json --debug=yes &
sleep 5

./mbtjsonin1 &
./mbtjsonin2 &
./mbtjsonin3 &

sleep 5

cat mbtjsonin.1.log
cat mbtjsonin.2.log
cat mbtjsonin.3.log

kill `cat /tmp/mbtpid`

# 'cat' server log sorted tot the output. Makes comparing easy
sort /tmp/mbtjsonserver.log
