#!/usr/bin/expect -f
#
spawn telnet localhost 2345
expect "Trying 127.0.0.1..."
expect "Connected to localhost."
expect "Escape character is '^]'."
expect { {"status":"ok"} }
log_file -noappend mbtjsonin.2.log
send { {"command":"tag", "sentence": [{"word":"Ik"},{"word":"niet"},{"word":"!"}] } }
send "\n"
expect -re ".*\]" # the send json
expect -re ".*\]" # the received json
send { {"command":"tag", "sentence": [{"word":"regel"},{"word":"twee"},{"word":"?"}] } }
send "\n"
expect -re ".*\]" # the send json
expect -re ".*\]" # the received json
log_file
