#!/bin/sh
#
# defaults:
#

mbts="$VG $mbt_bin/mbtserver"
 
$mbts --config=tests/mbt.cfg --logfile=/tmp/mbtserver2.log --pidfile=/tmp/mbtpid2 &
if test x"$VG" = "x"; then
  sleep 8
else
  sleep 80 # starting wotan takes long when VG-ing!
fi

./mbtserverin1 > tests/serv1.out &
./mbtserverin2 > tests/serv2.out &
./mbtserverin1 > tests/serv3.out &
./mbtserverin2 > tests/serv4.out &

if test x"$VG" = "x"; then
   sleep 30
else
   sleep 80
fi

cat tests/serv1.out
cat tests/serv2.out

kill `cat /tmp/mbtpid2`

# 'cat' server log sorted tot the output. Makes comparing easy
sort /tmp/mbtserver2.log


